gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The BAG is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

@
@ Coalesced strings meant to be used with automatic word-wrapping:
@

gText_lu_FoundAndPocketedOneItem::
	.string "{PLAYER} found one {STR_VAR_2}, and put it in the {STR_VAR_3} POCKET.$"

gText_lu_FoundAndBaggedOneItem::
	.string "{PLAYER} found one {STR_VAR_2}, and put it in the BAG.$"
   @
   @ This one seems to be used for the Battle Pyramid.

gText_lu_FoundAndPocketedOneTMHM::
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}, and put it in the {STR_VAR_3} POCKET.$"

gText_lu_FoundAndBaggedOneTMHM::
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}, and put it in the BAG.$"

gText_lu_FoundOneItemButBagFull::
	.string "{PLAYER} found one {STR_VAR_2}, but the BAG is full…$"
